# ======================================================
# Custom Detectron2 config for small object detection
# ======================================================

# _BASE_: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"

# ------------------------------------------------------
# INPUT
# ------------------------------------------------------
INPUT:
  MIN_SIZE_TRAIN: (0,)
  MAX_SIZE_TRAIN: 0
  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 0
  RANDOM_FLIP: "horizontal"
  CROP:
    ENABLED: False  # not recommended for small object

# ------------------------------------------------------
# MODEL
# ------------------------------------------------------
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  ANCHOR_GENERATOR:
    SIZES: [[8], [16], [32], [64], [128]]
    ASPECT_RATIOS: [[0.2, 0.5, 1.0, 2.0, 4.0]]
  RPN:
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
    NMS_THRESH_TEST: 0.05
    NUM_CLASSES:  1 # binary classification
    SCORE_THRESH_TEST: 0.3
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    POOLER_SAMPLING_RATIO: 0

# ------------------------------------------------------
# DATASETS
# ------------------------------------------------------
DATASETS:
  TRAIN: ("zod_traffic_sign_DE_train",)
  TEST: ("zod_traffic_sign_DE_val","zod_traffic_sign_PL_val")

# ------------------------------------------------------
# DATALOADER
# ------------------------------------------------------
DATALOADER:
  NUM_WORKERS: 12

# ------------------------------------------------------
# SOLVER
# ------------------------------------------------------
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00025
  MAX_ITER: 50_000  # for 20k images, b=8, epoch~20, for b=6, epoch~13, for b=4, epoch~10
  STEPS: [30000, 40000, 45000] 
  AMP:
    ENABLED: True        # GPU memory savings


TEST:
  EVAL_PERIOD: 5000
# ------------------------------------------------------
# OUTPUT
# ------------------------------------------------------
OUTPUT_DIR: "./output"